apiVersion: v1
kind: Secret

metadata:
  name: aws-credentials
  namespace: external-secrets

type: Opaque

stringData:
  access-key: TESTE
  secret-access-key: TESTE
  session-token: TESTE