apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.configMap.name }}"
  namespace: "{{ .Values.namespace }}"
data:
  FLAG_SERVICE_URL: "{{ .Values.configMap.data.FLAG_SERVICE_URL }}"
  TARGETING_SERVICE_URL: "{{ .Values.configMap.data.TARGETING_SERVICE_URL }}"