apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: analytics-secret
  namespace: analytics

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: analytics-secret
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: analytics-service