apiVersion: v1
kind: Service
metadata:
  name: flag-service
  namespace: "{{ .Values.namespace }}"
spec:
  type: ClusterIP
  selector:
    app: flag-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}