apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: auth-secret
  namespace: auth

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: auth-secret
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: auth-service