namespace: targeting-service

replicaCount: 1

image:
  repository: 975049924046.dkr.ecr.us-east-1.amazonaws.com/targeting-service
  tag: f34b10d
  pullPolicy: Always

service:
  port: 80
  targetPort: 8003

secret:
  name: targeting-secret

externalSecret:
  key: targeting-service  

configMap:
  name: targeting-config
  data:
    AUTH_SERVICE_URL: "http://172.20.9.142"
    
autoscaling:
  enabled: false  
