namespace: evaluation-service

replicaCount: 1

image:
  repository: 712979978195.dkr.ecr.us-east-1.amazonaws.com/evaluation-service
  tag: "42b8117"
  pullPolicy: Always

service:
  port: 80
  targetPort: 8004

secret:
  name: evaluation-secret

externalSecret:
  key: evaluation-service  

configMap:
  name: evaluation-config
  data:
    FLAG_SERVICE_URL: ""
    TARGETING_SERVICE_URL: ""
    
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70  
