namespace: evaluation-service

replicaCount: 1

image:
  repository: 712979978195.dkr.ecr.us-east-1.amazonaws.com/evaluation-service
  tag: "e7ae0b5"
  pullPolicy: Always

service:
  port: 80
  targetPort: 8004

secret:
  name: evaluation-secret

externalSecret:
  key: evaluation-service  

configMap:
  name: evaluation-config
  data:
    FLAG_SERVICE_URL: "http://172.20.136.148"
    TARGETING_SERVICE_URL: "http://172.20.222.50"
    
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70  
