apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: targeting-secret
  namespace: targeting

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: targeting-secret
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: targeting-service