apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tech-challenge-f3
  namespace: argocd

spec:
  description: Projeto Tech Challenge F3

  sourceRepos:
    - '*'

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'