apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tech-challenge-f3
  namespace: argocd

spec:
  description: Projeto Tech Challenge F3

  sourceRepos:
    - https://github.com/Erik-SJ/tech-challenge-f3.git
    - https://charts.external-secrets.io

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  orphanedResources:
    warn: true    

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'