name: Analytics Service CI

on:
  push:
    branches: [main]
    paths:
      - "apps/analytics-service/**"

  pull_request:
    branches: [main]
    paths:
      - "apps/analytics-service/**"

env:
  SERVICE_NAME: analytics-service
  SERVICE_PATH: apps/analytics-service
  AWS_REGION: us-east-1

jobs:

  build-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/analytics-service

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: |
          pip install pytest

      - run: |
          pytest || true

  lint:
    needs: build-test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/analytics-service

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          pip install flake8

      - run: |
          flake8 .

  security:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      ## SAST
      - run: |
          pip install bandit

      - run: |
          bandit -r apps/analytics-service

      ## SCA
      - uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: apps/analytics-service
          severity: CRITICAL
          exit-code: "1"

  docker:
    needs: security
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate Tag
        run: |
          echo "IMAGE_TAG=v1.0.0-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - uses: aws-actions/amazon-ecr-login@v2

      - run: |
          docker build \
            -t $SERVICE_NAME:$IMAGE_TAG \
            apps/analytics-service

      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.SERVICE_NAME }}:${{ env.IMAGE_TAG }}
          severity: CRITICAL
          exit-code: "1"

      - run: |
          docker tag \
          $SERVICE_NAME:$IMAGE_TAG \
          ${{ secrets.ECR_REGISTRY }}/$SERVICE_NAME:$IMAGE_TAG

      - run: |
          docker push \
          ${{ secrets.ECR_REGISTRY }}/$SERVICE_NAME:$IMAGE_TAG
